apiVersion: v1
kind: Service
metadata:
  name: {{ include "lastping.fullname" . }}-api
  labels:
    {{- include "lastping.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ include "lastping.fullname" . }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
