"""add check fields and slo targets

Revision ID: 0019_add_advanced_checks_and_slo
Revises: 0018_add_audit_fields_and_backfill_group_id
Create Date: 2026-01-25 21:16:02.415969

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0019_add_advanced_checks_and_slo'
down_revision = '0018_add_audit_fields_and_backfill_group_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('host', sa.String(), nullable=True))
    op.add_column('check', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('check', sa.Column('dns_record_type', sa.String(), nullable=True))
    op.add_column('check', sa.Column('latency_threshold_ms', sa.Integer(), nullable=True))
    op.add_column('check', sa.Column('last_latency_ms', sa.Float(), nullable=True))
    op.add_column('check', sa.Column('region', sa.String(), nullable=True))
    op.add_column('project', sa.Column('slo_target', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('sla_target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'sla_target')
    op.drop_column('project', 'slo_target')
    op.drop_column('check', 'region')
    op.drop_column('check', 'last_latency_ms')
    op.drop_column('check', 'latency_threshold_ms')
    op.drop_column('check', 'dns_record_type')
    op.drop_column('check', 'port')
    op.drop_column('check', 'host')
    # ### end Alembic commands ###
