"""create service table

Revision ID: 8814686d38e1
Revises:
Create Date: 2026-08-20 17:57:24.979295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8814686d38e1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum("http", "https", "tcp", "ping", "dns", name="monitor_type"),
            nullable=False,
        ),
        sa.Column("target", sa.String(length=2048), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("is_paused", sa.Boolean(), nullable=False),
        sa.Column(
            "current_status",
            sa.Enum(
                "unknown",
                "healthy",
                "degraded",
                "down",
                "paused",
                name="service_status",
            ),
            nullable=False,
        ),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_name"), "service", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_service_name"), table_name="service")
    op.drop_table("service")

    service_status = sa.Enum(
        "unknown",
        "healthy",
        "degraded",
        "down",
        "paused",
        name="service_status",
    )
    service_status.drop(op.get_bind(), checkfirst=True)

    monitor_type = sa.Enum(
        "http",
        "https",
        "tcp",
        "ping",
        "dns",
        name="monitor_type",
    )
    monitor_type.drop(op.get_bind(), checkfirst=True)
