plugins {
    id 'java'
    id 'maven-publish'
}

group = 'lastping'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'lastping-sdk'
        }
    }
}
