api:
  replicas: 1

workers:
  - name: staging
    replicas: 1
    env:
      - name: RUN_MIGRATIONS
        value: "0"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: staging.lastping.example.com
      paths:
        - path: /
          pathType: Prefix
