api:
  replicas: 2

workers:
  - name: us-east
    replicas: 1
    env:
      - name: RUN_MIGRATIONS
        value: "0"
      - name: WORKER_REGION
        value: "us-east"
      - name: WORKER_ID
        value: "us-east-1"
      - name: WORKER_REGION_FAILOVER
        value: "1"
  - name: eu-west
    replicas: 1
    env:
      - name: RUN_MIGRATIONS
        value: "0"
      - name: WORKER_REGION
        value: "eu-west"
      - name: WORKER_ID
        value: "eu-west-1"
      - name: WORKER_REGION_FAILOVER
        value: "1"
  - name: ap-south
    replicas: 1
    env:
      - name: RUN_MIGRATIONS
        value: "0"
      - name: WORKER_REGION
        value: "ap-south"
      - name: WORKER_ID
        value: "ap-south-1"
      - name: WORKER_REGION_FAILOVER
        value: "1"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: status.lastping.example.com
      paths:
        - path: /
          pathType: Prefix
